#!/usr/bin/env bash
# Regenerates the evidence reports in evidence/ by running each scenario
# (poc/E-*.sh) in a disposable container. Nothing runs on the host itself.
#
#   poc/run.sh              all scenarios
#   poc/run.sh E-05 E-11    selected scenarios
#   UMC_POC_DISTRO=rocky9 poc/run.sh E-08
set -euo pipefail
REPO=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)
distro=${UMC_POC_DISTRO:-debian12}
out=$REPO/poc/.out
mkdir -p "$out" "$REPO/evidence"

# v1 for the before/after comparisons comes from the git tag, not the tree.
git -C "$REPO" show v1.0:umc.sh > "$out/v1-umc.sh" 2>/dev/null || rm -f "$out/v1-umc.sh"

if ! docker image inspect "umc-test:$distro" >/dev/null 2>&1; then
    "$REPO/tests/run-in-docker.sh" "$distro" -- --count >/dev/null
fi
commit=$(git -C "$REPO" rev-parse --short HEAD)
git -C "$REPO" diff --quiet -- umc.sh || commit+="+local-changes"

scen=()
if (($#)); then for id; do scen+=("$(ls "$REPO"/poc/"$id"-*.sh)"); done
else scen=("$REPO"/poc/E-*.sh); fi

for s in "${scen[@]}"; do
    base=$(basename "$s" .sh) id=${base%%-[a-z]*}
    title=$(sed -n 's/^# TITLE: //p' "$s")
    claim=$(sed -n 's/^# CLAIM: //p' "$s")
    method=$(sed -n 's/^# METHOD: //p' "$s")
    dargs=$(sed -n 's/^# DOCKER: //p' "$s")
    echo "==> $id  $title"
    log=$out/$base.log
    # shellcheck disable=SC2086  # extra docker options are word-split on purpose
    docker run --rm $dargs -v "$REPO:/src:ro" -v "$out:/out:ro" "umc-test:$distro" bash "/src/poc/$base.sh" > "$log" 2>&1 || true
    envl=$(sed -n 's/^ENV: //p' "$log" | head -1)
    v=$(grep -E '^VERDICT:' "$log" | tail -1 | sed 's/^VERDICT: //')
    mark="❌ $v"; [[ $v == PASS ]] && mark="✅ PASS"
    {
        printf '# %s · %s\n\n' "$id" "$title"
        printf '| | |\n|---|---|\n'
        printf '| **Claim** | %s |\n' "$claim"
        printf '| **Method** | %s |\n' "$method"
        printf '| **Environment** | %s · UMC `%s` · %s |\n' "${envl:-unknown}" "$commit" "$(date -u +%Y-%m-%d)"
        printf '| **Reproduce** | `UMC_POC_DISTRO=%s poc/run.sh %s` |\n' "$distro" "$id"
        printf '| **Verdict** | %s |\n\n' "$mark"
        printf '## Output\n\n```text\n'
        grep -vE '^(ENV|VERDICT): ' "$log" | sed 's/\x1b\[[0-9;]*[A-Za-z]//g'
        printf '```\n'
    } > "$REPO/evidence/$base.md"
    echo "    $mark  -> evidence/$base.md"
done

# Index
{
    printf '# Evidence\n\nEvery claim in the README links here. Each report is generated by a script in\n'
    printf '`poc/` that runs in a throw-away container; re-run any of them with the command shown in it.\n\n'
    printf '| ID | Claim | Verdict |\n|---|---|---|\n'
    for f in "$REPO"/evidence/E-*.md; do
        [[ -f $f ]] || continue
        t=$(head -1 "$f" | sed 's/^# //')
        v=$(grep -m1 '^| \*\*Verdict\*\*' "$f" | sed 's/^| \*\*Verdict\*\* | //; s/ |$//')
        printf '| [%s](%s) | %s | %s |\n' "${t%% ·*}" "$(basename "$f")" "${t#* · }" "$v"
    done
    printf '\nE-16 comes from real VMs (SELinux enforcing, sshd, PAM, systemd) and is generated by\n`tests/vagrant/verify.sh`, which also removes every box it downloaded.\n'
} > "$REPO/evidence/README.md"
